### ISSUE TITLE
How to Add Pex File?

### ISSUE THREAD

**Issue by Chronos2086** [autch/piemu#2]
Hi I'm Trying To Figure Out How To Add Pex Files to Piemu.  I'm on Windows. I've Read This:

{"Steps to install PEX files to the flash image

tools/pffs or tools/pfar is the tool to add/remove files to/from piece.pfi image file.

$ pffs piece.pfi -adelv files...

    -a: add file(s) to pfi
    -d: delete file(s) from pfi
    -e: extract file(s) from pfi
    -l: list files in pfi
    -v: show system information in pfi"}

But I don't Really understand it. The pffs exe doesn't do anything for me.

**Comment by autch** [comment]
1. copy `pffs.exe` and PEX files to the folder where `piece.pfi` is placed
1. open Command Prompt, then `cd` to the directory where `piece.pfi` is placed
1. enter command `pffs -a piece.pfi FILENAME.pex` to write `FILENAME.pex` into `piece.pfi`

some recent branches have `pfar.exe` instead of `pffs.exe`, they are the same command line syntax.

**Comment by Chronos2086** [comment]
Got it. Thanks!
